name: CI
env:
  PROJECT_NAME: web_calc 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  pull_request:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codeStyle:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Python Style Checker
        id: autopep8
        uses: peter-evans/autopep8@v1
        with: 
          args: --ignore E402

  tests:
    runs-on: ubuntu-latest
    needs: [codeStyle]
    
    steps:
      - uses: actions/checkout@v2
        
      - name: echo
        run: |
          ls -a
          pwd  
        
      - name: runTests
        run: |
          pip install -e '.[test]'
          pip install coverage
          python -m coverage run -m pytest
          python -m coverage report
        # python3 -m venv venv
        # apt-get install python3-venv
        # python -m pip install coverage

  CI:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [tests]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Print docker version
      run: ls -a

    # Runs a set of commands using the runners shell
    - name: Docker build
      run: |
        docker build -t marinafs/$PROJECT_NAME:v_$GITHUB_RUN_NUMBER .
        docker images
        
    - name: Upload to docker hub
      run: |
        docker login --username=${{ secrets.DOCKER_LOGIN }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.USERNAME }}/$PROJECT_NAME:v_$GITHUB_RUN_NUMBER
        
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: kill old docker project
        run: docker kill $PROJECT_NAME
        continue-on-error: true
      
      - name: run project
        run: docker run -d --rm --name $PROJECT_NAME -p 5000:5000 ${{ secrets.USERNAME }}/$PROJECT_NAME:v_$GITHUB_RUN_NUMBER

      - name: end_to_end_testing
        run: |
          sleep 30
          curl -IS localhost:5000
                  
  Deploy_prod:
    runs-on: self-hosted
    needs: [CD]
    timeout-minutes: 3
    steps:
      - name: kill old docker project
        run: docker kill $PROJECT_NAME
        continue-on-error: true
      
      - name: run project
        run: docker run -d --rm --name $PROJECT_NAME -p 5000:5000 ${{ secrets.USERNAME }}/$PROJECT_NAME:v_$GITHUB_RUN_NUMBER
